File = main.cpp Polynomial.cpp
OutputFile = main

CC = g++

RunComand = ./

all: Compile Run Clear

Compile:
	$(CC) $(File) -o $(OutputFile)

Run: Compile
	$(RunComand)$(OutputFile)


Clear:
	rm $(OutputFile)
